# Generated by Django 3.2.11 on 2022-02-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220203_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_name_de',
            new_name='author_name_kz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body_text_de',
            new_name='body_text_kz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_de',
            new_name='title_kz',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_name_ky',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_text_ky',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ky',
        ),
    ]
